const IDENTIFIER = '/user/';

export const LOGIN = `${IDENTIFIER}LOGIN`;
export const LOGOUT = `${IDENTIFIER}LOGOUT`;

export const USER_LOGGED_IN = `${IDENTIFIER}USER_LOGGED_IN`;
export const USER_LOGGED_OUT = `${IDENTIFIER}USER_LOGGED_OUT`;

export const SAVE_USER_REQUEST = `${IDENTIFIER}SAVE_USER_REQUEST`;
export const SAVE_USER_SUCCESS = `${IDENTIFIER}SAVE_USER_SUCCESS`;
export const SAVE_USER_FAILED = `${IDENTIFIER}SAVE_USER_FAILED`;

export const SAVE_TOKEN_FAILED = `${IDENTIFIER}SAVE_TOKEN_FAILED`;
export const SAVE_TOKEN_SUCCESS = `${IDENTIFIER}SAVE_TOKEN_SUCCESS`;
